mutation CreatePublicMovieList($name: String!, $description: String) @auth(level: PUBLIC, insecureReason: "This mutation is safe to expose to the public") {
  movieList_insert(data: {
    name: $name,
    description: $description,
    isPublic: true,
    userId_expr: "uuidV4()", # Dummy value, as public lists don't belong to a user
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}

query GetMyPrivateMovieLists @auth(level: USER) {
  movieLists(where: { userId: { eq_expr: "auth.uid" }, isPublic: { eq: false } }) {
    id
    name
    description
  }
}

mutation AddMovieToMyList($movieListId: UUID!, $movieId: UUID!, $position: Int!) @auth(level: USER) {
  movieListEntry_insert(data: {
    movieListId: $movieListId,
    movieId: $movieId,
    position: $position
  })
}

mutation DeleteMyReview($id: UUID!) @auth(level: USER) {
  review_delete(key: {id: $id})
}